export enum SteamSessionEventType {
  LOGIN_SUCCESS = 0,
  LOGIN_FAILURE = 1,
  LOGIN_FAILURE_OTHER_SESSION_ACTIVE = 2,
  DISCONNECTED = 3,
  DISCONNECTED_SHOULD_RELOGIN = 4
}

export enum GameSessionEventType {
  CONNECTED = 0,
  DISCONNECTED = 1,
  DISCONNECTED_SHOULD_RELOGIN = 2
}
