export enum SteamSessionEventType {
  LOGIN_SUCCESS = 0,
  LOGIN_FAILURE = 1,
  LOGIN_FAILURE_OTHER_SESSION_ACTIVE = 2,
  DISCONNECTED_LOGOUT = 3,
  DISCONNECTED = 4,
  DISCONNECTED_SHOULD_RELOGIN = 5,
  LOGIN_CACHE_SUCCESS = 6
}

export enum GameSessionEventType {
  CONNECTED = 0,
  DISCONNECTED = 1,
  DISCONNECTED_SHOULD_RELOGIN = 2
}

export enum UserSessionType {
  NONE = 0,
  CACHE = 1,
  LOGGED_IN_ONLINE = 2,
  LOGGED_IN_OFFLINE = 3
}
